### PR TITLE
Add Makefile to providers for par creation

### PR DESCRIPTION
**Pull request by ChrisRx**
A Makefile at the root provides targets for copying the common Cross.toml and provider makefiles to all the providers.

This also adds a README.md indicating some basic usage and caveats on platform support.

### CODE REVIEW

**Comment by brooksmtownsend** [comment]
If you just run `make`, does it run the `build` step and the `par` step? (in that order) Just curious, LGTM

**Review by brooksmtownsend — APPROVED** [review]

**Comment by autodidaddict** [comment]
Is this still active as a draft?

**Comment by billyoung** [comment]
should we consider adding the `oras` push to this makefile? `make par` followed by a `make push`?

**Comment by autodidaddict** [comment]
Should `make push` here use oras or should it use wash? :)

**Comment by billyoung** [comment]
:joy: @autodidaddict yes... `wash`. It should definitely use `wash` :)

**Review by brooksmtownsend — APPROVED** [review]
LGTM, README looks good

**Pull request merged**
